package test.studynetwork;

/**
 * Much of this code is auto-generated by Android Studio
 * Portions of functions and whole functions have been edited
 * TODO: Update WorkingVersion as necessary
 * TODO: Display Profile information from Database
 * WorkingVersion 0.0.1
 * Written for GUI/Database Collaborative Project
 * The StudyNetwork LoginActivity
 * Created by Kristofor on 4/19/2015.
 */



import android.content.Intent;
import android.support.v7.app.ActionBarActivity;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;

public class ProfileActivity extends ActionBarActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_profile);
        getGroups();
    }

    public void buttonOnClick(View v)
    {
        //Not working...
        ListView myList = (ListView) findViewById(R.id.groupListView);
        //TODO: Move to study group information page on click
        myList.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                getView(position, view, parent);
            }
        });
    }



    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_profile, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }

    public void getGroups() {
        String[] contain = {"a", "b", "c"};

        ArrayAdapter<String> groupAdapter = new ArrayAdapter<String>(this, android.R.layout.simple_list_item_1, contain);
        final ListView myList = (ListView) findViewById(R.id.groupListView);
        myList.setAdapter(groupAdapter);
     }


    public View getView(final int position, View convertView, final ViewGroup parent) {
        //should be used to move the view from the list to the studygroup page. Not hooked into
        //anything on the application at the moment. 
        convertView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(final View v) {
                startActivity(new Intent(ProfileActivity.this, StudyGroupViewer.class));
            }
        });

        return convertView;
    }

}
