package test.studynetwork;

/**
 * Much of this code is auto-generated by Android Studio
 * Portions of functions and whole functions have been edited
 * TODO: Update WorkingVersion as necessary
 * TODO: Display Profile information from Database
 * WorkingVersion 0.0.1
 * Written for GUI/Database Collaborative Project
 * The StudyNetwork LoginActivity
 * Created by Kristofor on 4/19/2015.
 */



import android.support.v7.app.ActionBarActivity;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;


public class ProfileActivity extends ActionBarActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_profile);
    }

    public void buttonOnClick(View v)
    {
        //TODO: Make the fields editable
    }



    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_profile, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }
}
